urls:

   # cron jobs with GAE framework environment
 - url: cron
   run: site.cron

   # homepage
 - url:
   run: page.render
   arg: {template: welcome}


# site configuration
language: en
languages: [en, fr, de, ru, ua]


# redefine configuration for each application
apps:
  user:
    admins: [admin]
