urls:

- url:
  run: user.users_list
  short_name: users_list

- url: login
  run: user.login
  short_name: login

- url: logout
  run: user.logout
  short_name: logout

- url: registration
  run: user.registration
  short_name: registration

- url: (user)
  run: user.user_profile
  short_name: user_profile

# application specific configuration
admins: []