urls:
- url: add
  run: comments.create_comment
  short_name: create_comment

#- url: comment/posted
#  run: comments.comment_done

#- url: comment/flag/(comment_id)
#  run: comments.flag

#- url: comment/flagged
#  run: comments.flag_done

#- url: comment/delete/(comment_id)
#  run: comments.delete

#- url: comment/deleted
#  run: comments.delete_done

#- url: comment/moderate
#  run: comments.moderation_queue

#- url: comment/approve/(comment_id)
#  run: comments.approve

#- url: comment/approved
#  run: comments.approve_done


widgets:
  comments_list:
    default:
      can_create: true
      can_create_anonymous: true
      show_comments: true
      show_comments_anonumous: true
      