urls:
- url:
  run: user_profile

- url: login
  run: login

- url: logout
  run: logout

- url: registration
  run: registration

- url: :user
  run: user_profile

# application specific configuration
admins: [admin]