application: my-app-id
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on
- appstats: on

handlers:
# cron jobs (allow to run only automatically)
- url: /cron
  script: apps/site/cron.py
  login: admin
# serving static files: static/app_name/... -> apps/app_name/static/...
- url: /static/(\w+)/(.*)
  static_files: apps/\1/static/\2
  upload: apps/(\w+)/static/(.*)
# site favicon
- url: /favicon.ico
  static_files: apps/site/static/img/favicon.ico
  upload: apps/site/static/img/favicon.ico
# run GAE framework request handler
- url: /.*
  script: main.py